### ISSUE TITLE
Delete methods are not consistent with API 

### ISSUE THREAD

**Issue by beataj-telenav** [maproulette/maproulette2#104]
In the Project/Challenge/Task API the delete methods are described to return “204 NoContent”, but the delete methods returns instead a status code “200” with content {"message":"Challenge 40 deleted by user 21."}
Either correct the documentation or the delete method implementation.

**Comment by mgcuthbert** [comment]
The documentation for the API will be shifting to Swagger, instead of the markdown document that we have. So I am closing this and referencing the Swagger issue that we will be focusing on completing. This will have the correct 200 status code for the delete methods.

#96
