### ISSUE TITLE
 Challenge creation - default difficulty level not set

### ISSUE THREAD

**Issue by beataj-telenav** [maproulette/maproulette2#105]
The default difficulty level is not set if the challenge JSON does not specifies the difficulty field.
Request:
 {
  "name": "Misnamed Double Digitized Ways",
  "parent": 2,
  "identifier": "misnameddoubledigitizedways",
  "description": "",
  "blurb": "Double digitized ways with inconsistent naming",
  "instruction": "Fix the inconsistent naming of what seems to be a single double-digitized road.",
  "help": ""
}

Response:
  {"id":30,"name":"Misnamed Double Digitized Ways","description":"","parent":2,"instruction":"Fix the inconsistent naming of what seems to be a single double-digitized road.","blurb":"Double digitized ways with inconsistent naming","enabled":true,"challengeType":1,"featured":false}

**Comment by mgcuthbert** [comment]
Fixed in latest PR.
