### ISSUE TITLE
Challenge creation fails if no parent identifier is provided

### ISSUE THREAD

**Issue by beataj-telenav** [maproulette/maproulette2#107]
The challenge creation fails if no parent identifier is provided in the request JSON.

Request JSON:
{
  "name": "Misnamed Double Digitized Ways",
  "identifier": "misnameddoubledigitizedways",
  "difficulty": 2,
  "description": "",
  "blurb": "Double digitized ways with inconsistent naming",
  "instruction": "Fix the inconsistent naming of what seems to be a single double-digitized road.",
  "help": ""
}

Response JSON:
{"status":"KO","message":{"obj.parent":[{"msg":["error.path.missing"],"args":[],responseCode:400}],responseCode:400},responseCode:400}

Expected behaviour:
 The challenge is created into the default project (as described in the API).

**Comment by mgcuthbert** [comment]
Fixed per PR #132
