### ISSUE TITLE
Add missing information to API documentation

### ISSUE THREAD

**Issue by beataj-telenav** [maproulette/maproulette2#109]
Please update the API documentation to reflect the latest MapRoulette implementation details:
- there is no information regarding authentication; it is not clear that a consummer needs to send an API key in the header for each API call
- the delete method response it is not consistent with the actual implementation; these methods does not return "204 NoContent"
- in the case of the batch create/update methods the response description is missing from the API, it is not clear if the method will return a "201 Created" status or something else
- it is not clear from the documentation that only a super user can consume the Project API methods
- the "help" field of the Challenge entity it is not described in the API
- the “instruction” field of the Challenge it seems to be required (if you don’t send it you get an error); in the API should be specified that it is required 
- the "geometries" field of the Challenge entity is not described in the API

**Comment by mgcuthbert** [comment]
Thanks for looking at this. In the hopefully very near future we will remove the API documentations and rely entirely on Swagger for keeping our API documentation up to date.

**Comment by mvexel** [comment]
We will handle this in #96
