### ISSUE TITLE
Listing challenges method does not work

### ISSUE THREAD

**Issue by beataj-telenav** [maproulette/maproulette2#111]
Calling the  listing challenges method (http://maproulette.org:8080/api/v2/challenges) produce the following error:
 {
"status": "KO",
"message": "ERROR: missing FROM-clause entry for table \"parent\"\n  Position: 84"
}

**Comment by mgcuthbert** [comment]
Nice catch, I will fix this shortly.

**Comment by mgcuthbert** [comment]
Fixed per latest PR merge.
