### ISSUE TITLE
Error in iD link creation in Old Airports challenge

### ISSUE THREAD

**Issue by nvkelso** [maproulette/maproulette2#112]
It is:

* http://www.openstreetmap.org/edit?editor=id

Should be corrected to something more like:

* http://www.openstreetmap.org/edit?node=369154534&editor=id

```
@id: "node/369154534"
ele: "1209"
name: "Nixon Landing Strip"
aeroway: "aerodrome"
addr:state: "NV"
source_ref: "geonames.usgs.gov"
gnis:created: "03/01/1991"
gnis:feature_id: "848347"
gnis:county_name: "Washoe"
gnis:feature_type: "Airport"
```

**Comment by nicolas17** [comment]
I think this is because the feature properties have `@id` but the code is looking for `osmid`.

**Comment by mvexel** [comment]
This will be handled in #77
