### ISSUE TITLE
Use survey pretty name in all UX places

### ISSUE THREAD

**Issue by nvkelso** [maproulette/maproulette2#113]
When looking at my new survey:
http://maproulette.org:8080/ui/admin/list/project

I created a new survey called `Test nvk`, but here it shows as:

* 35	Home_131996

I expected it to be something more like:

52	Test nvk

Which I can see when I click on the `Home_131996` link.

**Comment by nvkelso** [comment]
I guess this is because the survey needs to be in a project? So maybe default the project name to the survey or challenge name?

**Comment by mgcuthbert** [comment]
35 Home_131996 is the name of your project, if you had to click on that link it would then list your challenges and surveys that you have created within that project. A survey is simply a variation of a challenge which is a child of the project parent.
