### ISSUE TITLE
Batch task creation method fails 

### ISSUE THREAD

**Issue by beataj-telenav** [maproulette/maproulette2#116]
Steps to reproduce:
- upload 1000 tasks to a challenge, see file:
  [geojson.txt](https://github.com/maproulette/maproulette2/files/312411/geojson.txt)

Expected  behaviour:
- tasks are uploaded to the challenge 

Actual behaviour:
- the upload operation fails with the following message:
  {"status":"KO","message":"ERROR: index row size 3520 exceeds maximum 2712 for index \"idx_tasks_parent_id_name\"\n  Hint: Values larger than 1/3 of a buffer page cannot be indexed.\nConsider a function index of an MD5 hash of the value, or use full text indexing.\n  Where: SQL statement \"INSERT INTO tasks (name, parent_id, instruction) VALUES (task_name, task_parent_id, task_instruction) RETURNING id\"\nPL/pgSQL function create_update_task(text,bigint,text,integer,bigint,text) line 8 at SQL statement",responseCode:500}

**Comment by mgcuthbert** [comment]
Your name in one of your tasks I noticed is "280. In the way(s): 417934783, 418009489 the folowwing segments: [64.072459,-84.118794:64.071942,-84.117912] are overlapping", which seems either more like a description or an instruction. The error message could be a lot clearer and I should probably enforce a much shorter name length than the allowed 2700 length. If you keep it below 2500 you will be fine, but I would suggest making them much shorter.

**Comment by mvexel** [comment]
@beataj-telenav after following @mgcuthbert's advice, is this now resolved?
