### ISSUE TITLE
Can't change geometry input format for cloned challenge

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#124]
A cloned challenge is 'forced' to use the same geometry consumption scheme as the challenge it's cloned from. Is it possible to make this changeable?

**Comment by Frankkkkk** [comment]
Had the same issue just now.

**Comment by mvexel** [comment]
I guess it depends how we define 'cloning' If we just clone the main properties (page 1) and leave the rest undefined, I think it is doable. The way challenges are modeled, they are assigned a type upon initial creation, which is immutable. The cloned challenge right now inherits that.

**Comment by mvexel** [comment]
I think we can close this as 'by design'. Cloning a challenge would mean that you would expect this challenge to be very similar, not something completely different. In that case you would start a new challenge anyway. Closing.
