### ISSUE TITLE
Ubuntu local setup

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#127]
Let's capture issues with local setup on Ubuntu here. @Kopkins

**Comment by Kopkins** [comment]
Local instance fails with server on login
Ubuntu 14.04 with postgresql 9.3

**Comment by Kopkins** [comment]
Updating postgresql to 9.5 still fails

**Comment by Kopkins** [comment]
Running on virtual machine with fresh install of Arch Linux and postgresql 9.5.3 works

Will try on fresh install of Ubuntu 14.04

**Comment by Kopkins** [comment]
Ubuntu 14.04 does not have good integration with postgresql 9.5.

Running on Ubuntu 16.04 with postgresql 9.5 cannot connect to database
localhost:9000 cannot load
This seems like it is a configuration issue so I am looking into it

**Comment by Kopkins** [comment]
For some reason the osm data base user was not getting the password set using `createuser -sW osm`

I want to try this again on a clean install making sure to follow the exact commands to see if the password does not get set

**Comment by mvexel** [comment]
Thanks for looking into this @Kopkins !

I fired up a 14.04 EC2 but haven't had a chance to really get going with it yet..

**Comment by Kopkins** [comment]
For `createuser` the `-W` flag is for a password needed to access the database. To set the user password we need the `-P` flag. I don't know if this is the same on a Mac. I'll submit a PR to update the documentation
