### ISSUE TITLE
Task details does not fit in white marker

### ISSUE THREAD

**Issue by tBeata-grab** [maproulette/maproulette2#129]
In some situations the details of a selected task, does not if in the white marker window:
 ![taskdetails_bug](https://cloud.githubusercontent.com/assets/13517512/16075246/cd5d1806-32f6-11e6-85a9-f812db92c656.png)

**Comment by mvexel** [comment]
We should probably clip this.

**Comment by reichg** [comment]
Looks like this has been addressed?
