### ISSUE TITLE
MapQuest layers will require API key & Leaflet plugin soon

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#130]
Per the below message to OSM `talk` earlier.

We should either remove the MQ layers (I don't consider them high value) or figure something out with them.

> MapQuest is moving to a 100% cloud solution - the new infrastructure dictates that all tile access will require a key. Details on how to get keys, SDKs and general migration information is below:
> 
> On Monday, July 11, 2016, our direct tile access to MapQuest legacy maps will be discontinued. After Monday, July 11, 2016, we’ll require those using our direct tiles access to sign up for a plan on the Developer Network and transition to one of our four mapping solutions:
> MapQuest plugin for Leaflet
> iOS mobile SDK
> Android mobile SDK
> Static map API
> 
> Get new keys and SDKs here:  https://developer.mapquest.com/
> 
> FAQ and details are below. If you have additional questions about these changes, please email us at developer-services@mapquest.com or contact us via our forum (URL below).
> 
> FAQ:
> 
> If I don’t sign up for a new AppKey, will my service be shut off?
> If you’re currently getting direct tile access, your service will be shut off beginning Monday,  July 11, 2016. We encourage you to sign up for a plan to access an AppKey and access our various mapping solutions.
> 
> What are the differences between the plans you offer?
> The available plans include: Free, Basic, Plus, Business, Business Enhanced, Business Plus, and Business Plus Enhanced. Please see our plans page for pricing and additional information. We also offer an Enterprise-level plan that includes additional benefits and flexibility. If you are interested in an Enterprise-level plan, please contact us to discuss licensing options.
> 
> How are transactions counted within your mapping solutions?
> A map transaction is generally generated under the following circumstances:
> The initial load of the map when using SDKs such as the JavaScript Maps API, Leaflet Plugins, Mobile SDKS, or legacy Flash Maps API
> There is a change in zoom level
> There is a change in map type, for instance, a change from the default map to satellite imagery
> The user pans and causes more than 40% of the displayed map to change (legacy Flash Maps API only).
> A request is made to the Static Map API Web Service.
> 
> What if I need help with the transition to a new mapping solution?
> Please visit the forums on our Developer Network if you have questions about transitioning from direct tile access to Leaflet, Mobile SDK or Static Map API.
> https://developer.mapquest.com/forum
> 
> -- 
> Jeff Medaugh Product Manager - Developer Services 
> MapQuest

**Comment by mvexel** [comment]
I vote remove btw ;)

**Comment by mgcuthbert** [comment]
I am fine with removing, so I will remove it from the layers.

**Comment by mgcuthbert** [comment]
Removed per PR #132
