### ISSUE TITLE
User settings

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#135]
User should be able to set their desired
* default base map layer (unless overridden by challenge)
* default editor

more?

**Comment by mgcuthbert** [comment]
This was fix in PR #168, the settings a user can set are the following:
Default base map layer including custom option for a tile server other than OSM, OpenCycleMap or Bing. (A Challenge can override this)
Default Editor (iD, JOSM, JOSM with new layer)
Locale
Theme (Just different color scheme for the site)
