### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#138]
This ticket tracks the design and development of the advanced challenge search. Let's discuss search parameters and design issues here.

**Comment by jschleuss** [comment]
Hi gang! I like the idea of a "search by area" query. I also like the idea of a better search. Could a field of "tags" be added to the challenge item so users could tag challenges with searchable queries? And maybe the description should be required to pick up more words?

**Comment by mgcuthbert** [comment]
The advanced search now allows various ways to search for challenges. You can search by challenge name, by project name, by challenge tags and by area. To search by area, you just check the "Use map bounds" option and then zoom to the area of the map you want to limit you search in and click the search button. For challenge name, you can either just type in text in the search bar and click enter, if you want to use the challenge name with other options you use the keyword challenge:<SEARCH_TEXT> and then following it with the search text directly after (no spaces). Project name and tags are similar except you would always use the keywords project: and tags:
