### ISSUE TITLE
increase session timeout

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#142]
This is too short now. We can make it 24 or even 48 hours.

**Comment by mgcuthbert** [comment]
I added recently the ability to have it never time out by setting the value to -1. As it was driving me crazy during development. So I can switch it to that, as this is a session cookie we are dropping.

**Comment by jschleuss** [comment]
Great! I'm also bugged by the one hour or so timeout. Though, it's probably a good reminder to move around.

**Comment by mgcuthbert** [comment]
This has been previously fixed.
