### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#147]
We should have a localized application and the localization should be easy to contribute to.

Consider using the same system that OSM uses for l18n

**Comment by mvexel** [comment]
OSM uses Transifex

**Comment by mvexel** [comment]
https://www.transifex.com/openstreetmap/public/

**Comment by mgcuthbert** [comment]
I had a fairly substantial update in PR #151. This basically sets the foundation for Internationalization. The messages file in the conf directory now just needs to be translated into different languages to support the language. In saying that I did not update the Challenge Wizard as part of that update, just didn't have the time.

**Comment by mgcuthbert** [comment]
This issue is now fully complete for English. So closing on that basis. Any localization for specific languages can be opened in a separate issue.
