### ISSUE TITLE
Bug when entering challenge via link without being logged in

### ISSUE THREAD

**Issue by jschleuss** [maproulette/maproulette2#149]
I'm seeing a bug (Chrome, Mac) when I hit a challenge's URL without being logged in, which is common when I come back after a day of not working on a challenge.

I'm guessing the /map/NUMBER (without a slash at the end) is the challenge URL, something I'd share to others. 
For example: http://maproulette.org:8080/map/179

I'll sign in, grant access and be back to hit "Edit." I'll edit in iD and save my changes, come back and hit "I fixed it" to be transported to another challenge, usually #1 the aerodrome challenge.

**Comment by mvexel** [comment]
This seems to have been fixed along the way. @jschleuss feel free to reopen if you still encounter this.
