### ISSUE TITLE
Challenges not loading (JsResultException)

### ISSUE THREAD

**Issue by emailsson** [maproulette/maproulette2#157]
![image](https://cloud.githubusercontent.com/assets/17142614/16578276/e9b25dec-4299-11e6-9272-3e7ce2b8e6f1.png)

KO : JsResultException(errors:List((/location/top,List(ValidationError(List(error.path.missing),WrappedArray()))), (/location/left,List(ValidationError(List(error.path.missing),WrappedArray()))), (/location/bottom,List(ValidationError(List(error.path.missing),WrappedArray()))), (/location/right,List(ValidationError(List(error.path.missing),WrappedArray())))))

**Comment by mgcuthbert** [comment]
This has been resolved in #156 but has not been updated on maproulette.org:8080

**Comment by mvexel** [comment]
I will update the maproulette server now.
