### ISSUE TITLE
Get in touch with challenge author

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#160]
It would be super nice to be able to get in touch with the author of a challenge. This would require discussion: an in-app messaging system? just have challenge authors add their email address and provide a link to that? just provide the OSM ID and a link to message that user through OSM?

**Comment by mgcuthbert** [comment]
I wouldn't ordinarily say this, but in this case it would seem like using OSM to pass the message through might be the best option. I am not sure building a message app within MapRoulette would be a beneficial use of time when there is a perfectly acceptable solution in OSM. So we could have something like "Send Message to [OSM Username of Challenge Owner]" and then that link just takes them to the message page in openstreetmap.org. That is my vote anyway.

**Comment by mvexel** [comment]
Makes sense to me! Let's do it that way.

**Comment by mvexel** [comment]
Makes sense. This would relate to #218 .

**Comment by mgcuthbert** [comment]
This is partly resolved in PR #224, I will leave open for now as there may be more area's in the UI that could benefit from including links to the challenge owner.
