### ISSUE TITLE
JOSM keeps opening new Layers

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#163]
This should probably be a user setting -- some users prefer a new Layer in JOSM for each time MapRoulette loads a task area in JOSM, others want the same layer for each time JOSM opens from MapRoulette.

**Comment by mvexel** [comment]
To clarify this happens when I click the 'Edit in JOSM' button  not the 'Edit in new JOSM layer' button.

**Comment by mgcuthbert** [comment]
Fixed per PR #180
