### ISSUE TITLE
task instruction no longer shown

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#176]
Since the update of the task toast, the task instructions are no longer shown.

<img width="375" alt="screenshot 2016-07-16 08 48 03" src="https://cloud.githubusercontent.com/assets/120452/16895398/227b81d0-4b32-11e6-8184-ca600a9282a6.png">

**Comment by mgcuthbert** [comment]
I will definitely fix this next week.

**Comment by mgcuthbert** [comment]
Fixed in PR #179
