### ISSUE TITLE
Store prefered editor for editing

### ISSUE THREAD

**Issue by Frankkkkk** [maproulette/maproulette2#182]
It's annoying to always click on the editor someone wants when we click on edit. We could manage that only with some JS and localStorage

**Comment by mvexel** [comment]
This is already fixed in #135  - we store this in the user settings and editing is now only one click. Does that address your issue @Frankkkkk ?

**Comment by Frankkkkk** [comment]
Indeed, browsing the source code I found that there was a user prefs panel. It wasn't shown clearly because my "User image" doesn't show. Maybe we could show the link more clearly (glyphicons, …) ?

**Comment by mvexel** [comment]
Okay closing here then. If you want to submit another issue for the user images go ahead.
