### ISSUE TITLE
Imagery not showing up

### ISSUE THREAD

**Issue by aawiseman** [maproulette/maproulette2#186]
When I start working on a project the basemap is just gray, no imagery or OSM or anything. I've tried a few different projects. I'm using Safari.

**Comment by ianmcorvidae** [comment]
I've experienced this as well with zoom levels 17 or greater. Seems to work fine on z16 though. I notice that I also can't switch imagery at the closer zooms, so it may be that support for those zoom levels is broken somehow.

**Comment by aawiseman** [comment]
@ianmcorvidae that's what I've experienced too. It shows up when I zoom out, but that's tricky for small features like buildings.

**Comment by mgcuthbert** [comment]
Resolved by PR #203

**Comment by aawiseman** [comment]
@mgcuthbert awesome! thanks
