### ISSUE TITLE
max / default zoom levels

### ISSUE THREAD

**Issue by martijnv-telenav** [maproulette/maproulette2#194]
It appears that the max zoom level set for a challenge is used as the default zoom level and the default zoom level is ignored. 

Also zoom level 19 does not make sense for all base maps, I notice that osm.org tiles do not load consistently on that zoom level. So suggesting that the default zoom level tops out at 18.

**Comment by ianmcorvidae** [comment]
I think this is related somehow to #186 but I'm not completely sure how. Just to be sure whoever fixes either bug is aware of the other!

**Comment by mgcuthbert** [comment]
Resolved in PR #203
