### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#212]
I generated certificates through LetsEncrypt, they sit in `etc/letsencrypt` on the server. Can we [deploy these in the application](https://www.playframework.com/documentation/2.5.x/ConfiguringHttps)?

**Comment by mvexel** [comment]
The main use case for this is third party web applications wanting to interact with the MapRoulette API, crossdomain restrictions usually don't allow mixed HTTP / HTTPS content any more, and more and more web sites are hosted on HTTPS only.

**Comment by mvexel** [comment]
This is becoming more urgent now that OpenStreetMap.org is moving away from http support.

**Comment by rugk** [comment]
https://github.com/openstreetmap/operations/issues/117

https://doesmysiteneedhttps.com/
https://scotthelme.co.uk/still-think-you-dont-need-https/

You need HTTPS for geolocation in modern browsers.

**Comment by mgcuthbert** [comment]
This is now completed. MapRoulette is now HTTPS only.
