### ISSUE TITLE
Error 500 on adding new task

### ISSUE THREAD

**Issue by gardster** [maproulette/maproulette2#229]
I'm trying to create new challenge with tasks. When I'm try to add a single task to my challenge, I got 500 error.

```
Error: Internal Server Error: ERROR: insert or update on table "task_geometries" violates foreign key constraint "task_geometries_task_id_fkey" Detail: Key (task_id)=(1333350) is not present in table "tasks".```

**Comment by mvexel** [comment]
Have you been able to reproduce this? I have not... Feel free to re-open if you still have problems.
