### ISSUE TITLE
OSM member since... not retrieved or calculated correctly?

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#23]
![member](https://www.dropbox.com/s/gcx05upt8cv1hh6/Screenshot%202016-04-20%2015.18.59.png?dl=1)

I have been an OSM member since 2007

**Comment by Crashfreak** [comment]
So I am not sure if you changed the OSM provider details. Basically I have it pointing to api06.dev.openstreetmap.org, which would have a different member date. So if you didn't change that then that is most likely the reason it is incorrect.

**Comment by mvexel** [comment]
of course...duh
