### ISSUE TITLE
"Invalid geometry supplied for task"

### ISSUE THREAD

**Issue by joto** [maproulette/maproulette2#249]
I clicked on some tasks "Fix" button in the map view and only got a quickly flashing message "Invalid geometry supplied for task". No way for me to see the number of the task or so to report the problem. The map view went to the 0,0 point in the Atlantic and I was zoomed in very far. Now I can't zoom out as fas as usual, the "-" button is disabled two zoom levels farther in than I would expect.

**Comment by joto** [comment]
I tried again on the same task a bit later and now it works!?

**Comment by mvexel** [comment]
Curious. Haven't been able to reproduce. Closing now but if you see it re-appear please re-open!
