### ISSUE TITLE
Graphs in metrics more than slightly off ...

### ISSUE THREAD

**Issue by simonpoole** [maproulette/maproulette2#254]
Even after lots of head scratching I'm at a loss to explain what the graphs here have to do with the progress and status of the challenge in hand, except that the values increase over time.

Wit:
![maproulette](https://cloud.githubusercontent.com/assets/1011860/21294757/ec452958-c544-11e6-84a1-055c08ec1319.png)

**Comment by mvexel** [comment]
@simonpoole what did you expect to see vs what you are seeing?

**Comment by simonpoole** [comment]
Well potentially interesting numbers would be 

* daily count per category
* accumulated count per category per day

But looking at the numbers from the graphs it is neither. Take for example the "Fixed" graph,
the numbers are 20 + 40 + 70 + 100 + 140 + 170 + 180 = 720 so it is obviously not the daily rate, and 180 is not 585 either.

**Comment by mvexel** [comment]
You can switch between a cumulative display (what you're seeing here) and a bar graph that displays the daily counts per category. So we have both of the things you want already in place.
