### ISSUE TITLE
Position of "I fixed it" for JOSM users

### ISSUE THREAD

**Issue by simonpoole** [maproulette/maproulette2#255]
The position of the "I fixed it" button is extremely annoying for JOSM users, even the slightest amount of bounce or inadvertently double-clicking will cause the task to marked as completed.

**Comment by mvexel** [comment]
Can you clarify a bit? Are the post-fix buttons too small in general? Is the location of this button somehow inconvenient?

**Comment by simonpoole** [comment]
The "I fixed it button" is in the same position as the "Edit in JOSM" button.  Actually use maproulette to see the issue in real life.

**Comment by mvexel** [comment]
I appreciate you taking the time to leave feedback but please try to keep it friendly and encouraging, Simon.

I see your point now. You can prevent this particular from occurring by setting a default editor in your MapRoulette profile, that also saves you a click. I'm thinking about the design of the buttons more in general and will take this into account.

**Comment by mvexel** [comment]
I'll close this specific issue as we'll handle this as part of #220
