### ISSUE TITLE
application versioning

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#26]
Let's have semantic versioning for MapRoulette, and include the version string somewhere in the UI (can be hidden away in an about screen). We could start with 2.0.0.

**Comment by Crashfreak** [comment]
So we don't currently have any about page. Possibly something we could look into. So for now I placed the semantic versioning in the copyright notice on the footer.

**Comment by mvexel** [comment]
Sounds good. I don't know if we want an about screen really...But I'm not sure we want to keep the © footer either. For now this is a good place to have it. We'll deal with the © footer / about page in a separate issue. Some time.

**Comment by harry-wood** [comment]
I made a new issue https://github.com/maproulette/maproulette2/issues/282 because the "All right reserved" text seems wrong. Could just use the github repo (and README.md) as the place to hold all "about" content (link to it!)
