### ISSUE TITLE
Sorting in admin interface broken

### ISSUE THREAD

**Issue by joto** [maproulette/maproulette2#268]
When looking at the list of tasks in the admin interface some column headers have little arraw icons indicating that you can sort the table. The icons can be toggled between sorting "up" or "down", but that doesn't change anything.

**Comment by reichg** [comment]
This looks to be addressed can we close?

**Comment by mgcuthbert** [comment]
Yes, @joto if the issue persists please log further UI based issues in the maproulette3 repo, which is where the UI is. osmlab/maproulette3
