### ISSUE TITLE
ID mess

### ISSUE THREAD

**Issue by joto** [maproulette/maproulette2#269]
Can somebody explain to me how task IDs are supposed to work? The numbers I see in the admin task list don't seem to correspond to the numbers that `/api/v2/challenge/:id/tasks` reports.

**Comment by mvexel** [comment]
They match for me. Perhaps I'm misreading you. Can you provide an example?

**Comment by joto** [comment]
I can't reproduce this now myself. Looks okay. I remember seing IDs and/or names with totally different numbers. Will close this now and reopen if I can reproduce this again.
