### ISSUE TITLE
production deployment strategy

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#27]
How shall we proceed with production deployment? Is there one preferred way? 

Related documentation: 
* https://www.playframework.com/documentation/2.5.x/Deploying
* http://alvinalexander.com/scala/play-framework-deploying-application-production-server
* Perhaps http://web.ist.utl.pt/~joao.a.p.antunes/2014/08/18/automating-deployment-of-a-containerised-play-2-2-x-app-with-git-docker/ ?

Related: #3

**Comment by Crashfreak** [comment]
I have been moving in the direction of the third document that you listed. Currently I am building a Docker image and so it seems like it would make sense to move into that direction of automated deployment.

**Comment by mvexel** [comment]
Interesting, I have never really considered production deployments with Docker yet but why not? I am trying my own hand at it as well, for the sake of learning. Let's compare notes soon.

**Comment by mvexel** [comment]
I looked into this a bit today, this is the strategy I came up with:
* Use two linked containers
  * one plain vanilla PostGIS for the database, https://hub.docker.com/r/mdillon/postgis/
  * one for the packaged app, using `sbt docker:publishLocal`
To let the app talk to the DB, we probably need to change the way the JDBC URI is constructed. That part I hadn't gotten to yet. the linked DB container will broadcast environment variables that hold the database host and port, see https://docs.docker.com/engine/examples/postgresql_service/ and https://docs.docker.com/v1.8/userguide/dockerlinks/ . 

That's what I am figuring, wonder what you came up with @Crashfreak ?

**Comment by mvexel** [comment]
Another idea (unrelated to dockerizing per se) is to have a production application configuration that overrides the appropriate values in `application.conf` and is kept out of the SCM. According to the [documentation](https://www.playframework.com/documentation/2.5.x/ProductionConfiguration#General-configuration) this is easy to do. I created a template override conf file with just the values that might be overridden:

```
# This overrides MapRoulette settings to be used in a production environment.
#
# DO NOT add this file to SCM
#
# Invoke with -Dconfig.file=/path/to/prod.conf

include "application.conf"

play.crypto.secret="%APPLICATION_SECRET%"

db {
  default {
    url=XXXX
  }
}

maproulette {
  debug=false
}

osm {
  server="http://www.openstreetmap.org"
  consumerKey=XXXX
  consumerSecret=XXX
}

logger.application=INFO
```

**Comment by mgcuthbert** [comment]
I was actually doing something very similar within the docker image I am building.

**Comment by mgcuthbert** [comment]
There is now another repo maproulette/maproulette2-docker that allows a user to deploy the MapRoulette2 code using docker.
