### ISSUE TITLE
Deleting a task returns to page 1

### ISSUE THREAD

**Issue by RicoElectrico** [maproulette/maproulette2#277]
When I delete a task from a challenge, I get thrown back to page 1.
Now, when there are 150 pages (and there's no "Go to page X"), that can be a _little_ annoying.

**Comment by mgcuthbert** [comment]
The UI in maproulette2 will very shortly deprecated and all new development is happening on the new MapRoulette3 UI. If this is still an issue on MapRoulette3 please open an issue in that repo.
