### ISSUE TITLE
hashtags

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#28]
hashtags are becoming more visible and important in changeset comment. let's look at how we can pre-populate changeset comments with hashtags #maproulette #[challenge] etc.

**Comment by Crashfreak** [comment]
I have included a simple version as you described in the latest pull request. Basically it will include the hashtags #maproulette and #[challenge]. In the future we can either add the challenge tags as hash tags as well, or allow a user when creating a challenge to include a set of hashtags to be included in the comment.

**Comment by mgcuthbert** [comment]
I am going to leave this issue open, although the basic tenants of the issue has be resolved, I would like to extend the idea and allow challenge authors to define hashtags as well.

**Comment by mvexel** [comment]
I didn't see JOSM populate these in the changeset comment yet.

**Comment by mvexel** [comment]
Considering this resolved.
