### ISSUE TITLE
Featured challenges "Self-intersecting la" ran out of tasks

### ISSUE THREAD

**Issue by harry-wood** [maproulette/maproulette2#280]
Does everyone see the same featured challenges as me? I'm seeing "Self-intersecting la" which doesn't have any tasks (Red pop-up message "NotFound : No tasks found.")

so...  clearly that should not be featured any more

**Comment by mvexel** [comment]
I updated the featured list, now the 'Wrong role' one is featured so we can start fixing that more quickly.
