### ISSUE TITLE
"Copyright All rights reserved" footer

### ISSUE THREAD

**Issue by harry-wood** [maproulette/maproulette2#282]
The site has a footer _"Copyright © 2016 MapRoulette Version 2.0.2. All rights reserved."_

Who is reserving all rights of what? The version number would imply we're talking about the software, but the maproulette software is Apache Licensed (As with any open source license technically it's copyrighted yes, but it's specifically _not_ "all rights reserved")

So unless I'm misunderstanding, the footer would be better just saying "MapRoulette Version 2.0.2. (source code)" (link to github)

**Comment by mvexel** [comment]
Agreed it's meaningless and probably confusing. Quick fix to remove.
