### ISSUE TITLE
docker machine

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#3]
It would be neat to have a one-line local test docker machine.

**Comment by Crashfreak** [comment]
Yeah this is definitely something that I want to add once the foundation has been set. Shouldn't be very difficult to get that done.

**Comment by mvexel** [comment]
Found [this article](https://velvia.github.io/Docker-Scala-Sbt/) which may be helpful.

**Comment by mgcuthbert** [comment]
This has been added through the new repo maproulette/maproulette2-docker
