### ISSUE TITLE
Make localization/translation easier by creating translatable string files ( .po )

### ISSUE THREAD

**Issue by mxa** [maproulette/maproulette2#300]
Currently the strings are stored in https://github.com/maproulette/maproulette2/blob/master/conf/messages for an easier and faster translation by non-programmers. It could be beneficial to move this process to a platform like [transifex](https://www.transifex.com/) or [POEditor](https://poeditor.com/).

**Comment by mvexel** [comment]
I'd welcome help with this as I have no previous experience, but agree that it would be helpful. If someone wants to jump in and organize this that would be fantastic.

**Comment by mxa** [comment]
Maybe a first step would be to have that messages file in a format so that the Gtranslator .po editor can open it.

**Comment by mvexel** [comment]
That would require some changes in the code to read that format instead of the file it ingests currently. Are you able to help with that?

**Comment by mxa** [comment]
I don't have the time, and I think the first steps to translate the messages file have already started https://github.com/osm-korea/maproulette2/tree/master/conf

**Comment by mvexel** [comment]
Since we're getting translations from contributors, I guess it is easy enough as it is :) Closing for now.
