### ISSUE TITLE
Finding interesting challenges complicated/impossible

### ISSUE THREAD

**Issue by stoecker** [maproulette/maproulette2#303]
Based on Jochen's challenges I tried to find these using the Maproulette interface. I constantly fail. I get lost in other stuff and my only way back is to go to Jochen's site again and start from there.

Ideas to improve:
- Overview page showing all still active challenges and their authors
- Per user left side menu showing the last challenge one was active in (i.e. "My Latest")
- Bookmark a challenge

I case any of these features already exists I wasn't able to find it.

**Comment by mvexel** [comment]
Thanks. Yes this is an issue and we are discussing it in #214 . Closing this and copying your issue as a comment there.
