### ISSUE TITLE
Work on task without being signed in

### ISSUE THREAD

**Issue by JBosm** [maproulette/maproulette2#306]
I cannot work on a task without being signed in. 
I checked, osm.org allows you to modify (or, to be more specific, to open the area in JOSM) without being signed in. Would it be possible to do the same with MapRoulette? I kind of strongly dislike being identified on every site I visit.

**Comment by mvexel** [comment]
MapRoulette is a tool for fixing things in OSM. You can't fix things in OSM without being signed in. 

Technically you wouldn't need to be signed in to MapRoulette to see tasks and then edit them in OSM itself. MR benefits from users being signed in in a few different ways:

* You can see who last changed the task status and get in touch with that user.
* You can see who created a challenge and get in touch with that user.
* We can see how many unique OSM users participate in challenges

Please note that we don't store anything about you in MapRoulette that is not already public through the OSM API ([here's me](http://www.openstreetmap.org/api/0.6/user/8909)) except for your actions in MR (changing statuses for tasks, mainly).

If you want you can retrieve tasks through the MapRoulette API to work on them:

`curl -X GET -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 21cc7491-83c5-7fcf-2358-eaf51d023b90" "http://maproulette.org/api/v2/challenge/2419/tasks?limit=100"`
