### ISSUE TITLE
Images don't display in wiki

### ISSUE THREAD

**Issue by cliffordsnow** [maproulette/maproulette2#312]
The images only show a broken icon on the instructions for part 1 and 2. See https://github.com/maproulette/maproulette2/wiki/Introducing-New-MapRoulette---Part-1.-Creating-and-Maintaining-Challenges as an example.

**Comment by mvexel** [comment]
Yea, that's what you get from relying on Dropbox image URLs... I will update them to S3. Thanks for reporting.
