### ISSUE TITLE
deleting a challenge locks application

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#326]
when deleting a challenge through the admin interface, the database gets really busy for a really long time, probably performing a number of cascading delete operations which are expensive on large tables. should be more gentle.

**Comment by mgcuthbert** [comment]
This is something that has been addressed in the new UI. The current UI could still lock up on large deletes as it doesn't leverage the new API call that is a lot more gentle.

**Comment by mgcuthbert** [comment]
Old UI is deprecated and issue addressed in new UI, so closing issue.
