### ISSUE TITLE
Location=None if tags value has an escaped "

### ISSUE THREAD

**Issue by osmtools** [maproulette/maproulette2#327]
I've created [Challenge 2662](http://www.maproulette.org/ui/admin/list/1802/Challenge/tasks/2662), and there are some tasks with Location = None. I figured out, that all these have a tag with an escaped " in its value.

Overpass query:

    [out:json]
    ;
    area(3600051477)->.searchArea;
    (
      node
        ["tourism"="viewpoint"]
        ["direction"]
        ["direction"!~"^([0-9]+|([; ]*([0-9]+-[0-9]+)+)+|[NESW]+|[NESW]+-[NESW]+|south|east|west|north)$"]
        (area.searchArea);
    );
    out body geom qt;

results in

`...
{
  "type": "node",
  "id": 3773845499,
  "lat": 51.6535110,
  "lon": 10.3300990,
  "tags": {
    "description": "Blick über \"Alt-Herzberg\" in's Siebertal. Ebenfalls zu sehen der Grosse Knollen.",
    "description:de": "Blick über \"Alt-Herzberg\" in's Siebertal. Ebenfalls zu sehen der Grosse Knollen.",
    "description:en": "View over \"Old-Herzberg\" into the Sieber valley. Also to see the Grand Knollen.",
    "direction": "50–120",
    "name": "Aussichtspunkt Schlossberg",
    "tourism": "viewpoint"
  }
}, ...
`

and this results in

`
{"type":"FeatureCollection","features":null}
`

**Comment by mvexel** [comment]
That seems like a bug alright. Thanks for reporting.

**Comment by mgcuthbert** [comment]
I have tested this recently and it seems to be working. I used the overpass query to verify it worked in the current version, so I would suggest testing again to see if this is still an issue. If it is, please provide the exact steps to reproduce.

**Comment by osmtools** [comment]
Indeed, looks good now.
