### ISSUE TITLE
Create challenge - General Tab Tags - Tag already used

### ISSUE THREAD

**Issue by robybully** [maproulette/maproulette2#334]
If a user creates a new challenge,
In Administration - Edit Challenge is open,
General tab is open.
Insert e.g. "Wikipedia" into textfield "Tag" and
Click Next untill Challenge is completed and saved.

The following error is reported:
Oops! Something went wrong.

We will work on fixing that right away.
Click on the Map button to start mapping again right away.
Error: Internal Server Error: Tag with name Wikipedia already exists in the database

**Comment by mvexel** [comment]
Hi, that is a bug, thanks for reporting. The workaround for now is to not use tags for your challenge :(

**Comment by mgcuthbert** [comment]
This is resolved in the current build and deployed as part of Beta.3.
