### ISSUE TITLE
uneditable project name

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette2#336]
my default project name is ugly mix of pointless text and id (`Home_1722488`)

http://maproulette.org/ui/admin/form/project/-1/1986 has name field grayed out and it is impossible to edit it

it would be desirable to edit the project name (BTW, is it really necessary to have project at all? It is one additional layer of complexity without visible benefit - after all shared challenges may be listed together with other challenges, projects may be probably hidden from users)

**Comment by mvexel** [comment]
The project is not very meaningful for the average user, typically you only have one and you don't need to worry about it. So having it even visible is perhaps confusing. 

For 'power users' who have lots of challenges of different types it may be useful to have multiple Projects to group them. Right now you would have to request them by emailing / messaging me (or create an issue here.)

If you want your project renamed still, I can do that manually for you. For now I'll close this hoping I have answered your question :)

**Comment by matkoniecz** [comment]
I am not sure how complicated it would be - but maybe hide that projects exists from normal user?

Enabling visibility of both project and challenge is not something obvious, especially as enabling visibility of project is quite well hidden.

**Comment by mvexel** [comment]
We're probably going to improve this in the next UI overhaul. I'll add a tag to this ticket to track that.
