### ISSUE TITLE
images on wiki are not working

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette2#338]
for example in https://github.com/maproulette/maproulette2/wiki/Introducing-New-MapRoulette---Part-1.-Creating-and-Maintaining-Challenges#via-geojson section (and geojson anyway should probably appear as a text).

**Comment by mvexel** [comment]
Thanks for pointing that out.. I think something changed in the s3 configuraion. Let me look into it.

**Comment by mvexel** [comment]
Fixed
