### ISSUE TITLE
Make it possible to lock people into a task

### ISSUE THREAD

**Issue by joostschouppe** [maproulette/maproulette2#341]
We want to be able to work on a maproulette task e.g. during a mapathon, or for people who read a blog post. However, Maproulette will not just roulette through task but also challenges. So we need to be able to lock people up within our task.
(if this is out of scope, we might still run our own instance to achieve this)

**Comment by mgcuthbert** [comment]
Do you mean that when cycling through tasks in a challenge it serves up random tasks for other challenges, or literally that you want to be able to lock in specific users to specific challenges for some set period of time, or something like that?

Because if it is serving tasks from other challenges when you are looking at a specific challenge, then that would be a different kind of issue.

**Comment by joostschouppe** [comment]
From what I understand: current behavior is "cycle through tasks within a challenge for some time, then randomly switch to another challenge at some point". Or is this not current behavior anymore?

What I would like: a switch to enable "cycle through tasks within a challenge until there are no more tasks left". It would also be OK if it cycles through challenges within a Project.

**Comment by mgcuthbert** [comment]
Current behavior is: "Cycle through tasks within a single challenge until no tasks are available". Once no tasks are available a "No Tasks Found" will be displayed.

**Comment by joostschouppe** [comment]
Misunderstanding by me. Sorry.

**Comment by mgcuthbert** [comment]
No worries, if you do see it not working as expected please feel free to reopen.

**Comment by joostschouppe** [comment]
Just to be sure of one more thing: if there are other Challenges within the Project after you run out of Tasks within the Challenge, does it also show "No tasks found"? If so, is there a way to show a link on that page to the next Challenge within the project? Related: can you link to a Project, or only to Challenges?
(I'm asking because I'm thinking about the architecture of our project. Should we upload one huge JSON file with all the errors as one Challenge, or upload very many JSON files based on a zoomlevel 14 vector tile? See challenge 2786 for a demo. We will have at least daily updates available.)

**Comment by mgcuthbert** [comment]
To your first question yes, if no tasks are found within a challenge it will display "No tasks found" even if there are other challenges within a project. I think that is actually a great idea to suggest another challenge once you have completed one, and you should create an issue specifically for that. Also at the moment you can only link to Challenges and not Projects.

As for how to setup your challenges, either approach would work, so it would be completely up to you how you would like to manage it.

**Comment by joostschouppe** [comment]
OK, thanks. Looks like we'll go for the "upload one huge file through the API approach", so for now I'm happy. I will post a new issue as suggested.
