### ISSUE TITLE
Low priority: suggest-a-next-challenge

### ISSUE THREAD

**Issue by joostschouppe** [maproulette/maproulette2#344]
Upon finishing the last task in a challenge, I think you just randomly go to a different challenge (or you get a "no more tasks" warning). It would be nice if the author can suggest another challenge at that moment, or if they can choose to forward you to another Challenge within the same project.

**Comment by mvexel** [comment]
Interesting idea...Probably low prio as you already indicate. Perhaps someone else can help out implementing this!

**Comment by mgcuthbert** [comment]
If still have issue with this please transfer issue to https://github.com/osmlab/maproulette3, as the UI code all lives in that project.
