### ISSUE TITLE
Reload of maproulette always brings me back to last challenge

### ISSUE THREAD

**Issue by habi** [maproulette/maproulette2#346]
Whenever I reload maproulette, I'm logged out, after a second reload I'm logged in again.
The 'real' problem though is that whenever I reload the page no matter what challenge I select, I always get forwarded to the last one I did, e.g. I cannot start any new challenges.

Here's a little screencast showing my problem: http://youtu.be/2HpIWgwhwIM?hd=1

**Comment by mvexel** [comment]
This should be fixed in the next major release.

**Comment by habi** [comment]
Great! Do you have an ETA for that release?

**Comment by mvexel** [comment]
Within the next few weeks.

**Comment by mgcuthbert** [comment]
Closing UI issue, for all UI issue please see https://github.com/osmlab/maproulette3
