### ISSUE TITLE
Allow sharing management of Challenges or Projects

### ISSUE THREAD

**Issue by joostschouppe** [maproulette/maproulette2#347]
I have a Challenge linked to my OSM account. I would like to share management of this Challenge with other people. This seems to be impossible, so I made a new OSM account I can share. But then you still need to rebuild the enitre task, as there is no export/import function.

**Comment by mvexel** [comment]
Yea, that would be neat. I'll take that into consideration for the next version. @nrotstan @mgcuthbert  I suspect this would require a model change to allow multiple owners of a project, or do you see a simpler solution to Joost's issue?

**Comment by joostschouppe** [comment]
FWIW, we now just share one "OSM Belgium" OpenStreetMap-account for Maproulette and similar applications (like Mapcontrib). Once you know you need to work like that, it's no big deal.

**Comment by mgcuthbert** [comment]
This is now achievable in the new UI. The API also includes functionality to do this. So closing this issue as completed. See https://github.com/osmlab/maproulette3 for the UI implementation.
