### ISSUE TITLE
Repeated requests to log in

### ISSUE THREAD

**Issue by bborkmiller** [maproulette/maproulette2#352]
I'm not sure if this is a Maproulette issue or an OSM website issue, but every time I click Edit on a Maproulette challenge, I get prompted to log in. I do, make my edits, move on to the next item in Maproulette, click edit, and get prompted to log in again.

This is doubly peculiar because the OSM website knows I'm logged in: The user menu in the upper right hand shows my avatar and I can view my profile, etc. without having to log in.

I've tried logging out and logging back in a couple of times, and it hasn't fixed the problem.

**Comment by mvexel** [comment]
Hm. I can't reproduce. Can you try with a different browser? Check your cookie / privacy settings? (It doesn't sound like it's related to that since OSM 'knows' you're logged in...)

**Comment by bborkmiller** [comment]
Maybe it was a temporary cookie problem or something, because I can't reproduce it any more either. No changes on my end as far as I know, but anyhow it works now!

**Comment by mgcuthbert** [comment]
Please reopen if you experience this again. Thanks
