### ISSUE TITLE
Challenge changes after requiring login

### ISSUE THREAD

**Issue by xivk** [maproulette/maproulette2#353]
When logged in maproulette allows you to link to a challenge and it stays in that same challenge task after task.

When pointing new users to a challenge, they first need to login, after that the challenge is not locked anymore.

Step to reproduce:
- Go to maproulette.org and logout.
- Go to this challenge (or any other): http://maproulette.org/map/2789
- (it auto-selects first task)
- Login
- Skip task.
- Now you are in another challenge.

If you are already logged in the challenge stays the same.

**Comment by mvexel** [comment]
This should be fixed in the new version which is getting close to release. Bear with me :)

**Comment by xivk** [comment]
No problem, we're just logging whatever we (think we) find here. No pressure! 👍

**Comment by reichg** [comment]
Not able to repro this anymore?

**Comment by mgcuthbert** [comment]
Yes this should now be resolved.
