### ISSUE TITLE
Statistics on the dashboard don't seem to make sense

### ISSUE THREAD

**Issue by joostschouppe** [maproulette/maproulette2#358]
There seems to be a mismatch between what the graph and the numbers show about the map. See here 
 http://maproulette.org/ui/metrics/2789 or on the screenshot. The total fixed is about 500, but the graph seems to show only 120 fixed tasks.

![image](https://user-images.githubusercontent.com/10122639/33339920-e3d8e444-d47a-11e7-9105-15416b59348f.png)

**Comment by mvexel** [comment]
Joost -- the numbers you see are only for the time period selected. I do realize this is confusing. If you select a longer time period, you will see that the numbers from the chart correspond with the totals.

**Comment by joostschouppe** [comment]
Right! Sorry for using this page as a Help site.
Using a cumulative graph usually entails that the most recent number is the grand total. It might be more intuitive to work with a bar chart if this is the default view. Or change the default date range to start with the date of the first task mapped. Or show the total cumulative since the beginning, even if you only just show the last week.

**Comment by mgcuthbert** [comment]
So I am going to close this task, as in the new UI the metrics have been addressed in a different way and so these graphs won't exist after the beta period is over. If you have any issues in the new UI with the way metrics are displayed, or any misunderstandings with it, please open an issue in the maproulette3 project. Thanks.
