### ISSUE TITLE
Add banner to link to MR3 beta

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#383]
Now that we're going into beta, let's add a banner linking to the new version. 

It could just say 'See this task in MapRoulette 3 (beta)' if it's easy to link dynamically to the task. 

An easier way, also fine, would be to just have it say 'Try the new MapRoulette 3 beta!' and link to the main page of MR3.

**Comment by mgcuthbert** [comment]
I think to make it easy and simple, and just have "Try the new MapRoulette 3 beta".

**Comment by mgcuthbert** [comment]
This is now included in the bottom right hand corner
