### ISSUE TITLE
"Start" opens different challenge (bug)

### ISSUE THREAD

**Issue by sfkeller** [maproulette/maproulette2#385]
These challenges are no yet completed:
* Missing Crosswalks of Vaud in Switzerland (Switzerland)
* Missing Crosswalks of Geneva in Switzerland (Switzerland)
* Missing Crosswalks of Southern Switzerland (Switzerland)

When clicking on "Start" a completley different challenge occurs, like 
* "Challenge: Phone or fax number is not in international format (ITU-T E.164) - Sweden"
* "Challenge: Add Sidewalks Tags to Major SF Bay Area Roads"
* "Challenge: Connectivity Error in Mexico"

This did not happen before.

**Comment by arxcode** [comment]
I am having exactly the same problem, trying to add crosswalks in Berne (Switzerland) or fixing phone numbers.

**Comment by mgcuthbert** [comment]
This fix has been deployed, if it persists please reopen the issue.
