### ISSUE TITLE
403 Forbidden when creating a new challenge

### ISSUE THREAD

**Issue by andrewharvey** [maproulette/maproulette2#387]
Sorry if this is the wrong place to report this.

1. I visit http://maproulette.org/
2. I click Sign in and grant access at the OSM website, I'm now logged in to MapRoulette 2.1.0
3. I choose Projects and I have my Home Project ID `2380` name `Home_237525`.
4. I hit the dropdown button and choose New Challenge. The URL is now `http://maproulette.org/ui/admin/form/challenge/2380/-1` and it reports a:

```
403 Forbidden
Click on the Map button to start mapping again right away.
Error: Forbidden: User [2342] does not have access to this project [2380]
```

5. I noticed I'm no longer logged in and there is a button to Sign in, so I click Sign in and grant access again, and it goes back to the 403 page.

**Comment by mgcuthbert** [comment]
This issue should be resolved now. It was related to a bug introduced in one of the recent beta releases. If you experience this issue again, please reopen this issue.

**Comment by andrewharvey** [comment]
Thanks @mgcuthbert all good now.
