### ISSUE TITLE
Project admin challenge count incorrect

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#40]
I have a project with 1 challenge but the project overview says it has 0: 
<img width="1130" alt="screenshot 2016-05-12 14 49 03" src="https://cloud.githubusercontent.com/assets/120452/15229981/b6472c76-1850-11e6-829f-77af599f1523.png">
<img width="1118" alt="screenshot 2016-05-12 14 48 57" src="https://cloud.githubusercontent.com/assets/120452/15229982/b64a1576-1850-11e6-9efb-09b9c9fe0d08.png">

**Comment by mgcuthbert** [comment]
Yeah that actually hasn't been implemented yet, it was a placeholder. :)

**Comment by mgcuthbert** [comment]
Resolved in latest merged PR.
