### ISSUE TITLE
Clone a challenge

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#42]
It would be neat if you could clone a challenge. Would look like this:

![screenshot-2016-05-12-15 11 01](https://cloud.githubusercontent.com/assets/120452/15230719/6a86f7b8-1854-11e6-83bb-4a1df0331cc9.jpg)

Hitting 'Clone' would open the new challenge creation screen pre-populated with the values of the source  challenge.

Use case is when you have challenges that are very similar but require only small tweaks to description and / or overpass query.

**Comment by mgcuthbert** [comment]
Will be part of my next PR.

**Comment by mgcuthbert** [comment]
Added in most recent PR.
