### ISSUE TITLE
Website gives error 500 on login

### ISSUE THREAD

**Issue by sfo** [maproulette/maproulette2#421]
Every attempt to login results in the following error message:
```
500 Page Error
Oops! Something went wrong.
We will work on fixing that right away.
Click on the Map button to start mapping again right away.
Error: Internal Server Error: Communication with the service provider failed: Service provider responded in error: 301 (Moved Permanently)
```

Both, mr2 and mr3 are affected.
Browsers tested: Firefox and Google Chrome on Ubuntu 18.04. Google Chrome on Android

**Comment by joostschouppe** [comment]
I have the same issue. Tested Firefox and Chrome on Windows, and Chrome on Android.

**Comment by sfo** [comment]
@nrotstan In my opinion, it's still a bug in maproulette, which is not following the redirect. Therefore, handling this correctly should be the best solution, which is also more robust in case of future changes.

**Comment by mgcuthbert** [comment]
This is resolved in the latest deployment of MapRoulette. If you see any issues, please first clear your browser cache, as I noticed a bit during testing that it would store redirections that would then skip hitting the server.
