### ISSUE TITLE
Import tasks from GeoJSON

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#43]
It would be neat to have two ways of mass task generation for a challenge: Overpass (implemented) and GeoJSON import. GeoJSON could be either from a Gist ([example](https://gist.github.com/mvexel/a1c8513313d136c83cec89803857499a)), from geojson.io ([example](http://geojson.io/#id=gist:mvexel/975e64532cb5edf2ad28&map=10/53.7724/-2.7775)) or even pasting in a text field?

**Comment by mvexel** [comment]
Or a random URL, example: http://pgh.terrapattern.com/?lat=40.3902895&lng=-80.1144195

**Comment by mgcuthbert** [comment]
Fixed in recent PR.
