### ISSUE TITLE
Could not create challenge 

### ISSUE THREAD

**Issue by beataj-telenav** [maproulette/maproulette2#430]
Could not create a new challenge. Request example:
-  url:  http://maproulette.org/api/v2/challenge
- header: api key of the user osm-integrity-checks@telenav.com is sent
- body:
     {
        "name": "Dead Ends Test1345",
         "parent": 62,
         "difficulty": 1,
          "blurb": "Unexpected dead ends of major roads",
          "instruction": "Determine if the dead end ought to connect to something.",
          "defaultZoom": 18,
          "minZoom": 18,
           "maxZoom": 20,
           "enabled": false
     }

**Comment by mgcuthbert** [comment]
Could you please provide the error response that you are getting. I have tested this locally and the creation of the challenge works, so to further work out what is going I will need to understand what the exact failure you are getting is.

**Comment by beataj-telenav** [comment]
I got he following response: 
       {"status":"NotAuthorized","message":"Authorization failed (server replied with a 401). This can happen if the consumer key was not correct or the signatures did not match.",responseCode:401}.
We are using the MapRoulette API in one of our components (maproulett-loader) that creates/updates challenges & tasks from different map checks or ImproveOSM data.

**Comment by mgcuthbert** [comment]
Ok so I believe I know what is going on here. Recently we had to upgrade the backend framework and the encryption libraries we used were removed from PLAY, and so we had to replace them. This however means that old APIKey's would not work anymore. This will need to be fixed so that you can update the API_KEY in the new UI. As a workaround fix, you can go into the old UI using the url: http://maproulette.org/?oldui=true, and then going to your user profile and reseting the API KEY.

**Comment by beataj-telenav** [comment]
After I re-generate the API_KEY the issue was solved. Thank you!
However I have noticed that the created challenges are not showing up in http://maproulette.org/mr3/admin/projects . 
For example challenge http://maproulette.org/ui/admin/list/62/Challenge/tasks/3049 that is available in the old MapRoulette , it can not be found at the user's challenges in the new MapRoulette.
Our use case would be to create invisible challenges by default, after some QA the challenge is enabled to the OSM community.

**Comment by mgcuthbert** [comment]
If it is available in the old UI but not the new UI, then that would be an issue with the maproulette3 project. @nrotstan could you maybe comment on this one.

**Comment by nrotstan** [comment]
@beataj-telenav thanks for reporting this. It does indeed appear to be a bug with the new UI. I've opened up osmlab/maproulette3#396 to track it. As a temporary workaround, if you search for `dead` (or whatever challenge name you're looking for) in the "Project or Challenge Name" search box in the left sidebar on http://maproulette.org/mr3/admin/projects then it will hopefully present your new challenge to you as a search result after a couple seconds.

**Comment by mgcuthbert** [comment]
I am going to close this ticket, as it has been replaced with the ticket above.
