### ISSUE TITLE
create postman API test suite

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#44]
A Postman API test suite would be nice.

**Comment by mvexel** [comment]
This is taking shape at https://www.getpostman.com/collections/c89dec230de3bdc2c25f

**Comment by mvexel** [comment]
Once we have a Swagger UI this may not be as urgent ( #96 )

**Comment by mgcuthbert** [comment]
#159 PR added a start to the API test suite. I made some changes that touched basically every single file and so felt it would be good to have something that I could run very quickly that would test the whole system.
