### ISSUE TITLE
Error creating new challenge

### ISSUE THREAD

**Issue by beataj-telenav** [maproulette/maproulette2#445]
Creating a new challenge fails with the following error:
 {
   "status": "KO",
  "message": "ERROR: syntax error at or near "$14" Position: 684"
}
Request url:  http://maproulette.org/api/v2/challenge
Request body: 
  {
     "name": "Road Islands in US2345",
     "parent": 62,
     "difficulty": 1,
     "blurb": "Disconnected road networks of at least 10 edges but not more than 100 edges",
     "instruction": "Determine if the island ought to connect to something.",
     "defaultZoom": 18,
     "minZoom": 17,
     "maxZoom": 20,
      "enabled": false
  }

**Comment by nrotstan** [comment]
Thanks for reporting this, @beataj-telenav!  It'll be addressed by PR #446.

**Comment by beataj-telenav** [comment]
Thank you :)
