### ISSUE TITLE
[Documentation] Create challange link does not work

### ISSUE THREAD

**Issue by habi** [maproulette/maproulette2#503]
I'd love to generate a challenge and wanted to read up on how to do this.
In the [README](https://github.com/maproulette/maproulette2/blob/master/README.md) you link to the [wiki](https://github.com/maproulette/maproulette2/wiki) for further information.
But the wiki states that there is "No information here".

Where can we find this information?

**Comment by nrotstan** [comment]
Hi @habi, there are some help resources on the MapRoulette 3 wiki. maproulette.org uses the v3 UI.
https://github.com/osmlab/maproulette3/wiki/Help-and-Resources

Here is an overview of creating a challenge using v3: https://www.openstreetmap.org/user/mvexel/diary/46863

If you need to use the old v2 UI, here is an overview of that:
https://github.com/maproulette/maproulette2/wiki/Creating-MapRoulette-Challenges-from-GeoJSON
