### ISSUE TITLE
Assigning user to different project doesn't work consistently

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#52]
Repro:
- Go to user admin
- Assign a project to a user
- Reload to see it worked
- Assign second project to a user
- Reload -- there is no indication that the second project was added to the user
- Add the first project to the user again -- silently fails

What I see happen is:
- You can actually add multiple projects to a user but this is not reflected in the UI
- When trying to add a project to a user, we don't check if the user already has that project, leading to an error. (Console says `GET http://maproulette.org:8080/auth/addUser/5/toProject/2 400 (Bad Request)`)

I think it actually makes much more sense to do the user administration for a project on the project page, so to have a 'Users' page where you can add and remove users from a project, next to the 'Challenges' and 'Surveys' tabs.

**Comment by mgcuthbert** [comment]
So a couple of these things have been addressed in recent checkins, however I don't want to close this as there probably needs more discussion around how it should work.
