### ISSUE TITLE
/api/v2/project/:id/children (undocumented)

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#53]
The undocumented API call `/api/v2/project/:id/children` does not give an invalid path response, but rather the following:

```json
{
  "status": "KO",
  "message": {
    "obj": [
      {
        "msg": [
          "error.expected.jsobject"
        ],
        "args": []
      }
    ]
  }
}
```

**Comment by mgcuthbert** [comment]
This is now documented in the Swagger UI and the response is valid. I still need to remove the old documentation as it is not necessary and out of date.
