### ISSUE TITLE
creating new project sometimes fails with duplicate key constraint violation

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#55]
Not sure how to reproduce yet, but getting this from time to time upon project creation through the API:

``` json
{
  "status": "KO",
  "message": "ERROR: duplicate key value violates unique constraint \"idx_groups_name\"\n  Detail: Key (lower(name::text))=(test project_admin) already exists."
}
```

**Comment by mgcuthbert** [comment]
Generally that error would indicate that there is already a project with the name you are providing. Project names have to be unique.

**Comment by mvexel** [comment]
Let's add a check after the first step for the name. Backlogging, manual project creation is not common and can only be done by superuser
