### ISSUE TITLE
Generating tasks from an overpass query involving ways and nodes will create a task for the way and each node in it

### ISSUE THREAD

**Issue by CloCkWeRX** [maproulette/maproulette2#560]
Example generated tasks:
https://maproulette.org/challenge/8118/task/18461979
https://maproulette.org/challenge/8118/task/18461980
https://maproulette.org/challenge/8118/task/18461975

![image](https://user-images.githubusercontent.com/365751/59083522-d36ebd00-8936-11e9-8f44-42302f1f8829.png)

Tasks will exist for each point in the polygon; as well as the overall way.

With the UI (https://github.com/osmlab/maproulette3/issues/732); this leads to a slightly discouraging user experience - you fix one problem, but if you load the next few nearby tasks, then have to skip them (multiple clicks).

**Comment by nrotstan** [comment]
Thanks for the report, @CloCkWeRX. This is an issue with the Overpass query. Please see the first bullet point in this comment for advice on fixing the query: https://github.com/osmlab/maproulette3/issues/721#issuecomment-485544079

I'm going to close this issue, but feel free to open it again if you think there is a MapRoulette bug.
