### ISSUE TITLE
API may not be building correctly?

### ISSUE THREAD

**Issue by sisskind** [maproulette/maproulette2#579]
Trying to deploy local version of MR2 and MR3.  I can create a new challenge, but when I try to create a task, it reports back that the task is locked, and I'm brought to a debug screen.

The specific request is `http://127.0.0.1:9000/api/v2/task/1204/start 400 (Bad Request)` and also `http://127.0.0.1:9000/api/v2/task/1204/release 400 (Bad Request)`.

When I try to insert `http://127.0.0.1:9000/api/v2/task/673/start` the response is `{"status":"KO", "message":"Invalid Path [task/672/start] for API"}` but using public maproulette, I get a JSON return of the task. (edited) 

My best (2 am) guess is that the API did not properly build, but I'm unsure if there is a way to rebuild without rebuilding the entire MR2 project?

**Comment by nrotstan** [comment]
Those `Invalid Path for API` errors sound like you're not running on the latest version of the backend code.

In development, the backend should automatically rebuild any modified files as needed when it processes the first http request it receives (this is usually pretty quick -- a handful of seconds). So if you pull down the latest code and make a request, it should rebuild if anything is new or changed. If you don't think that's happening for some reason, it's also possible to do an `sbt clean` to wipe everything and rebuild from scratch, but the ensuing build will take much longer.

If you're running off a production build, then you would need to rebuild after pulling down the latest code.

**Comment by sisskind** [comment]
Will try SBT clean. I was running off version 3.4.2 but will confirm that’s the case.

**Comment by nrotstan** [comment]
3.4.5 is the latest maproulette2 version. The latest MR3 release pretty much always assumes it's working with the latest maproulette2 release. If you grab the latest releases of each project, you should be good.

**Comment by sisskind** [comment]
@nrotstan you are a gentleman and a scholar.  Thought I had grabbed the right version, but that solved it.  Thanks so much!
