### ISSUE TITLE
Shared search result links do not work as expected.

### ISSUE THREAD

**Issue by govvin** [maproulette/maproulette2#610]
I'm trying to send someone a [link](https://maproulette.org/browse/challenges?challengeSearch=113.62060546875001%2C7.406047717076271%2C133.76953125000003%2C17.28770905062193&keywords=highway) of road-related challenges in my region, expecting that they will see a list of challenges that are related to the keyword. I expect them to have a similar result to what I got when I did the same search myself, like this:

![image](https://user-images.githubusercontent.com/5821688/64671007-a7188e80-d499-11e9-8bd8-c77433aa5d60.png)

However, when a user opens the link they get the default challenges, unrelated to the link:
![image](https://user-images.githubusercontent.com/5821688/64671073-d7f8c380-d499-11e9-84ef-2eaf3ddbd437.png)

**Comment by nrotstan** [comment]
Fixed in v3.4.1 release
