### ISSUE TITLE
Consider using marker popups instead of toast messages

### ISSUE THREAD

**Issue by iandees** [maproulette/maproulette2#65]
Instead of having a text box floating over to the side here:

![image](https://cloud.githubusercontent.com/assets/261584/15485392/e89d6a04-210c-11e6-977d-7ce09fb5ef67.png)

…consider putting that text in a Leaflet popup attached to the marker.

You'd want to let the user close that popup, so you'll have to think about where to put the text when they are finished skimming and decide to move the map around. Maybe when they dismiss the popup the text hides in the white area at the bottom of the page?

**Comment by mgcuthbert** [comment]
The only problem I see with your suggestion is that currently the popup is used to display properties for a given element. Often times this would be in the form of OSM tags that are associated with the feature.

**Comment by iandees** [comment]
Are you thinking of the case of a linear feature? In either case, having a popup point at the feature with custom information about that feature seems ideal, not a problem. Perhaps I'm misunderstanding your concern, though.

**Comment by mvexel** [comment]
Perhaps we can keep the current popup messages but prepend the OSM tags with the instruction, and have it pop up by default. And have a little header between the instruction and the OSM tags that just says 'OSM tags' or something.

**Comment by mgcuthbert** [comment]
My only concern in this scenario is that the popup could become really large. And the dual purpose of it may lead to misunderstanding.

**Comment by mvexel** [comment]
If the main purpose of this is to give more space for map real estate, we can just make the toast message clickable so that it disappears on click?

**Comment by iandees** [comment]
For me the main purpose is to call out the marker/area of interest, not to make more room on the map.

**Comment by mvexel** [comment]
In #66 we're discussing per-challenge settings. One of them would be custom text / markdown content.

**Comment by mvexel** [comment]
I think with the instructions sometimes being long and even containing images it makes more sense to draw attention to the feature of interest in some other way.
