### ISSUE TITLE
Default to a wider map view to give more context

### ISSUE THREAD

**Issue by iandees** [maproulette/maproulette2#66]
When viewing a marker the map is zoomed in all the way. This is good when editing, but in the MapRoulette task assignment view it might make more sense to zoom out a few notches to give the user some more context about where they are and what data is around the area of interest.

It might be that this is specific to the "Aerodrome in NC" project it's defaulting to (i.e. I need to zoom out to see if there's an airport or runway mapped next to this aerodrome node), but it feels generally applicable to me.

**Comment by mgcuthbert** [comment]
I think that is a good point, probably should create a default that makes sense, and then also allow challenges to override the default value.

**Comment by mvexel** [comment]
Yes. It would be good for challenges to be able to override the following things:

1) map zoom
2) UI collapse / expand
3) base map layer

other things?

**Comment by mvexel** [comment]
I am going to ask the Mapzen folks to see if they're interested in helping us think about this from a design perspective.

**Comment by mvexel** [comment]
rolling this into #102
