### ISSUE TITLE
Don't reload Overpass query if it didn't change?

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#68]
If you edit the details of a challenge, the Overpass query will be re-fired upon submitting the changes. This may not be what the user wants. Perhaps make it optional. Or add an 'reload overpass' option to the challenge admin menu to do this explicitly and never do it otherwise. Or add a date interval (every day / week) to schedule re-running the query.

**Comment by mgcuthbert** [comment]
I think a forced reload and schedule for overpass queries would both be good ideas.

**Comment by mgcuthbert** [comment]
Fixed in recent PR, however leaving open because I did not add any scheduling to update the overpass query or the remote url.

**Comment by mvexel** [comment]
Going to close this and create new ticket for scheduling Overpass queries to run at an interval the user can set.
