### ISSUE TITLE
API GET /challenge/{id}/tasks page params bug

### ISSUE THREAD

**Issue by dcastrowa** [maproulette/maproulette2#686]
There is an issue with fetching tasks from a challenge in batches using the limit and page parameters in the API. After changing the page number, the assumption is that it will fetch the next limit amount from a challenge but instead it fetches the same as the previous page.

**Example**:
https://maproulette.org/docs/swagger-ui/index.html?url=/assets/swagger.json#/Challenge/listChildren - GET /challenge/{id}/tasks
Challenge ID: 3907
Number of tasks: 10

Request URL page 0 - https://maproulette.org/api/v2/challenge/3907/tasks?limit=5&page=0
Ids that are returned:
- 13382843
- 13382844
- 13382845
- 13382846
- 13382847

Request URL page 1 - https://maproulette.org/api/v2/challenge/3907/tasks?limit=5&page=1
Ids that are returned:
- 13382844
- 13382845
- 13382846
- 13382847
- 13382848

**Comment by nrotstan** [comment]
The `page` parameter is poorly named. For that API endpoint it's actually an offset, e.g. page * limit.

**Comment by dcastrowa** [comment]
thank you!
