### ISSUE TITLE
Local version of MapRoulette

### ISSUE THREAD

**Issue by cieniu9** [maproulette/maproulette2#727]
Hi,

I am a total newbie and I would like to setup MapRoulette localy on my machine.
Can anyone list the things I need to do to run it on my localhost ?

Thanks in advance

**Comment by mvexel** [comment]
Hi, 
A good way to start is to use the [Docker setup](https://github.com/maproulette/maproulette2-docker).

**Comment by mgcuthbert** [comment]
Closing issue, please respond if the link above is not sufficient.
