### ISSUE TITLE
users list only goes up to 10, doesn't paginate

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#73]
There are 24 users in the DB when I just query it, but the users table shows 10 and says '1 to 10 of 10 entries'.

**Comment by mgcuthbert** [comment]
I found this bug earlier today actually. It is a fairly minor issue, a workaround before I get the fix in is to add ?limit=100 in the query string and then refreshing the page.

**Comment by mgcuthbert** [comment]
Fixed in recent PR.
