### ISSUE TITLE
metrics 'too hard to fix' should be skipped

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#74]
the user sees and clicks 'next' which is not necessarily the same as 'too hard to fix'. Suggest changing to 'skipped'.

**Comment by mgcuthbert** [comment]
So currently there really isn't a difference between "Skipped" and "Too hard to fix". So in an upcoming PR I will be changing the name of the "Next" button to "Skip" and it will set the status to "Skipped" and then in the edit box that comes up the "Too Hard" button will set a new status called "Too Hard", which will be reflected every else in the system as well.

**Comment by mgcuthbert** [comment]
Resolved with latest PR.
