### ISSUE TITLE
first load on mobile isn't great

### ISSUE THREAD

**Issue by eMerzh** [maproulette/maproulette2#76]
there is no way to close the info panel, 
the map seems to be half init 

and there is only part of the right menu

see below:

![tmp_25722-screenshot_20160525-2339011130266910](https://cloud.githubusercontent.com/assets/177003/15557270/774f0fa2-22d2-11e6-9e51-b4baf1721d3d.png)

**Comment by mvexel** [comment]
We didn't test on mobile at all. Mobile is not really a target use case for MapRoulette yet. I would love for it to be in the future, and to have location-aware ground survey specific challenges, but we are not there yet.

For now, I will close this, but let's revisit it when we get to supporting mobile and mobile challenges!
Thanks for reporting!
