### ISSUE TITLE
Escape comma in generated CSV

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette2#818]
I attempted te generate CSV to export tasks for review, unfortunately commas in fields are not escaped breaking its processing.

Happened in https://maproulette.org/admin/project/41014/challenge/13921

**Comment by matkoniecz** [comment]
Now I see that some are escaped correctly. I applied  additional workaround and MR2 is to be scrapped anyway, so reproducing this is not useful anyway.

**Comment by nrotstan** [comment]
I know the naming is confusing, but the maproulette3 project is only a frontend -- it still uses the backend from the maproulette2 project. So I'm going to reopen this. Thanks for the report, @matkoniecz !

**Comment by matkoniecz** [comment]
But MR2 is supposed to be deprecated, right?

Anyway, I am not sure what is happening - I opened one CSV extract in calc and had comma escaping isues, I rebuild tasks (some with commas were still present) and issue disappeared.

**Comment by nrotstan** [comment]
Ok, in that case I'll close it. Feel free to reopen if you do experience any additional issues with comma escaping.

Basically the maproulette2 project has morphed into the backend for maproulette3 (the old mr2 frontend was stripped out some time ago). One of these days we'll likely rename the maproulette3 and maproulette2 projects to something like mr-frontend and mr-backend, respectively, to better reflect their actual roles.
