### ISSUE TITLE
JsonValidationError when creating virtual challenge

### ISSUE THREAD

**Issue by shawat94** [maproulette/maproulette2#829]
When attempting to create a virtual challenge by selecting the 'Work on [x] Mapped Tasks' on the 'Find Challenges' page, a JsonValidationError is consistently returned:

![image](https://user-images.githubusercontent.com/33205894/90803964-668edb00-e2ce-11ea-90dc-15b5bba612d0.png)

**Comment by mgcuthbert** [comment]
This is probably related to the frontend, could you please file your issue here: https://github.com/osmlab/maproulette3/issues

**Comment by shawat94** [comment]
Thanks @mgcuthbert, I've moved the issue to the frontend repo: https://github.com/osmlab/maproulette3/issues/1373
