### ISSUE TITLE
wiki home page should link to maproulette3 docs

### ISSUE THREAD

**Issue by donalhunt** [maproulette/maproulette2#833]
URL: https://github.com/maproulette/maproulette2/wiki

There are still some links out there that bring you to maproulette v1 and v2. The maproulette2 wiki should link people to the most recent (or next major version - v3 won't be the most recent for ever). URL is https://github.com/osmlab/maproulette3/wiki

The source of my journey today was https://gist.github.com/mvexel/b5ad1cb0c91ac245ea3f which links to maproulette2 wiki (which is fine; one cannot continually update a deprecated document).

**Comment by mgcuthbert** [comment]
So in the maproulette2 wiki I have added a statement that basically telling them to go to https://github.com/osmlab/maproulette3/wiki for the latest information. Other than deprecated documentation, if there are any active links that we should change please let us know.

**Comment by donalhunt** [comment]
perfect. thanks!
