### ISSUE TITLE
Overpass Challenge with Timeout > 120s

### ISSUE THREAD

**Issue by boldtrn** [maproulette/maproulette2#842]
The [wiki](https://github.com/osmlab/maproulette3/wiki/Using-Overpass-to-create-Challenges) mentions users can increase the timeout. I wanted to create a chalenge that requires a timeout of 600. Maproulette showed me an error about a timeout at 120000, I guess that's ms.

For now I will simply fall back to upload a GeoJson, but having the option to actually pass an overpass query would be great.

**Comment by nrotstan** [comment]
Hi @boldtrn , specifying higher timeouts should generally work. What does your overpass query look like?

**Comment by boldtrn** [comment]
Thanks for the update @nrotstan. 

My overpass query looks something looks like this:
```
[timeout:600];
area[name="Deutschland"]->.e;
way(area.e)[highway~"^(motorway|trunk|primary|secondary|tertiary|(motorway|trunk|primary|secondary)_link)$"]->.major;
node(w.major)["barrier"~"^(gate|lift_gate|swing_gate)$"][!"access"];
out meta;
```

Essentially I am mapping nodes on ways, which is a rather expensive query.

I had the feeling that your fetch client might have a 2 minute timeout set?
