### ISSUE TITLE
MR server failing 

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette2#874]
```
Oops!

    Unable to retrieve latest challenge data from server.
    Unable to retrieve latest project data from server.
```

independent report from at least two different people

Maybe "MapRoulette will briefly go down for maintenance Thursday, 28th of January, at 20:00 UTC" started earlier?

**Comment by mgcuthbert** [comment]
This issue should be resolved now. Please open issue again if you see it again.
