### ISSUE TITLE
Feature request: Task/Challenge desctiptions point to markdown URL

### ISSUE THREAD

**Issue by herriotto** [maproulette/maproulette2#892]
Would it be possible to add functionality to set up task/challenge description/instructions to point to a url/markdown and load dynamically so a central set of instructions could be maintained.

**Comment by mvexel** [comment]
Hi, this seems to be a request pertaining to the MapRoulette front-end application. This is the repository specifically for the MapRoulette back-end and API. If you still would like to have this issue considered, kindly open an issue [on the main MapRoulette repository](https://github.com/osmlab/maproulette3/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+).
