### ISSUE TITLE
[bug] Unable to upload tasks using the /vs/tasks API after latest release.

### ISSUE THREAD

**Issue by atiannicelli** [maproulette/maproulette2#895]
After the latest update our program that we use to update and create projects and challenges no longer seems to be able to push tasks using the /v2/tasks/ API.
I don't see any errors (still trying to debug) but the same program was working before the update.

Basically I am able to create the project and challenges, but the challenges end up with no tasks.

Here is an example of the body of a POST that succeeded but I see no task in the challenge
```
[{
"instruction":"1. The railway (OSM ID: 429776488) has one or more car navigable intersections on the same layer that are missing intersection nodes. To fix: If highway crosses the railway at the same layer then make sure that there is a node connected to both railway and highway at the intersection with `railway=level_crossing` tag. If highway and railway are on different layers then update the appropriate layer tag for the way that goes under or over the other way.",
"name":"429776488000000",
"parent":18791,
"geometries":{"type":"FeatureCollection","features":[{"geometry":{"type":"Point","coordinates":[175.454017,-40.0391091]},"type":"Feature","properties":{}},{"type":"Feature","geometry":{"type":"Point","coordinates":[175.454017,-40.0391091]},"properties":{"synthetic_highlight_point":"yes","flag:check":"New Zealand - LevelCrossingOnRailwayCheck","flag:generator":"Atlas Checks"}},{"type":"Feature","geometry":{"type":"LineString","coordinates":[[175.4744477,-40.0245979],[175.473619,-40.02515],[175.4723771,-40.0256727],[175.468301,-40.027488],[175.467397,-40.027955],[175.466945,-40.028276],[175.466441,-40.028725],[175.461919,-40.033492],[175.460949,-40.034367],[175.446806,-40.044042],[175.445895,-40.044713],[175.445147,-40.04553],[175.444593,-40.046477],[175.442938,-40.049806],[175.44244,-40.05183],[175.4421602,-40.0523498],[175.44213,-40.052406],[175.441338,-40.053496],[175.441028,-40.054076],[175.44059,-40.055306],[175.440241,-40.056511],[175.440153,-40.057106],[175.440159,-40.058096],[175.440094,-40.058711],[175.439835,-40.059508],[175.439513,-40.060076],[175.438867,-40.06092],[175.438516,-40.061467],[175.437995,-40.062836],[175.437698,-40.063398],[175.437304,-40.063919],[175.436816,-40.06439],[175.436048,-40.064928],[175.435152,-40.065361],[175.4343417,-40.0656859],[175.4171953,-40.0725868]]},"properties":{"gauge":"1067","last_edit_changeset":"100741116","identifier":"429776488000000","itemType":"Line","iso_country_code":"NZL","osmIdentifier":"429776488","usage":"main","operator":"KiwiRail","voltage":"25000","frequency":"50","last_edit_user_name":"Kelerei","electrified":"contact_line","last_edit_time":"1615345503000","last_edit_user_id":"233136","name":"North Island Main Trunk","railway":"rail","last_edit_version":"2"}}]}
}]
```

I posted that ^^^ body to the /v2/tasks API on the swagger page (https://maproulette.org/docs/swagger-ui/index.html?url=/assets/swagger.json#/) and I received a good response.
```
{
  "status": "OK",
  "message": "Items created and updated"
}
```

but no tasks were added to the challenge as viewed through the gui: https://maproulette.org/browse/challenges/18791

**Comment by Bentleysb** [comment]
I am seeing this same thing as well. Has the geometries property changed for the task json? I'm seeing that in the swagger example is marked a string, but classically it is a geojson geometry object.

**Comment by jschwarz2030** [comment]
A PR is up to resolve the issue.  Apologies for the bug.

> I am seeing this same thing as well. Has the geometries property changed for the task json? I'm seeing that in the swagger example is marked a string, but classically it is a geojson geometry object.

This is unrelated to the issue but a good question.  The endpoint accepts both a string or an object.  The Task Model in the API requires a string, but the Task services do the conversion automatically, depending on the data type provided.  Providing an object seems much more user friendly to me, so this is my guess as to why it was made that way.

**Comment by atiannicelli** [comment]
@jschwarz2030 thanks for the fix! Could this be a candidate for a hotfix prior to the normal monthly release?

**Comment by jschwarz2030** [comment]
Yes we are deploying a patch update early this week.
