### ISSUE TITLE
API key visibility to end user

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#92]
The toast message with the API key shows up for only a brief time. Either we make something that has a 'copy to clipboard' button or we make the toast message sticky. Alternatively we just show this in the User info panel directly. Ideas?

**Comment by mgcuthbert** [comment]
I think showing it in the User Info panel, and then later in the User Profile as well is probably the best way to do it. No real need to make it a toast message.

**Comment by mgcuthbert** [comment]
Fixed in PR #172
