### ISSUE TITLE
History panel shows wrong element

### ISSUE THREAD

**Issue by tordans** [maproulette/maproulette2#943]
Example: https://maproulette.org/admin/project/47829/challenge/26808/task/127866219/inspect
Shows the history of https://www.openstreetmap.org/node/576351107/history
However, the area in question is https://www.openstreetmap.org/way/576351107/history (same ID, but way instead of node)

The project is set up using an overpass query using `out center`.
```
[out:json][timeout:25];
(
  node["landuse"="village_green"]["check_date"!~".*"](52.17898456576359,12.84576416015625,52.80193116968236,14.02130126953125);
  way["landuse"="village_green"]["check_date"!~".*"](52.17898456576359,12.84576416015625,52.80193116968236,14.02130126953125);
  relation["landuse"="village_green"]["check_date"!~".*"](52.17898456576359,12.84576416015625,52.80193116968236,14.02130126953125);
);
out center;
```

I use that, since no using it mean that I had a task for every node of an area, which was not what I wanted.

Since I use out center, I had the "overpass taget typ" on "does not matter" ("Egal", maybe "Any?").
I just tried changing that to "way", which results in the error "Element type Some(relation) does not match target type of 'way'".

The overpass result of that query https://overpass-turbo.eu/s/1h9M _does_ show that it is a way.

```js
{
  "version": 0.6,
  "generator": "Overpass API 0.7.57.1 74a55df1",
  "osm3s": {
    "timestamp_osm_base": "2022-03-26T12:23:45Z",
    "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL."
  },
  "elements": [
{
  "type": "way",
  "id": 43159167,
  "center": {
    "lat": 52.5160907,
    "lon": 13.4075824
  },
  "nodes": [
    5527537479,
    5527537478,
    5527537477,
    5527537480,
    5527537481,
    5527537474,
    5527537475,
    6256331823,
    6256331824,
    5527537472,
    6256331825,
    5527537473,
    6256331826,
    5527537479
  ],
  "tags": {
    "landuse": "village_green"
  }
}

  ]
}
```

So I assume, the history-Panel could be fixed by making it look at the actual JSON element `type`.

**Comment by mvexel** [comment]
Hi @tordans 

This looks to be more of a MapRoulette front-end issue than an API issue. Could you please resubmit here: https://github.com/osmlab/maproulette3/issues 

Thanks!
