### ISSUE TITLE
OSM notes as challlenges

### ISSUE THREAD

**Issue by Binnette** [maproulette/maproulette2#945]
I am wondering if this is possible to create a Maproulette challenge based on a JSON file of OSM notes. This kind of challenge should simply show the note to the user, allow him to edit the map and then automatically close the note if the user mark the Maproulette challenge as solved.

I am interested in this feature, cause we can create a subset of notes and create a Maproulette challenge with it. For exemple if I request all the note containing a text like "update with imagery", I can create a nice challenge in Maproulette.

**Comment by matheusgomesms** [comment]
Hi @Binnette, we created a similar issue here: [https://github.com/osmlab/maproulette3/issues/1711](https://github.com/osmlab/maproulette3/issues/1711). Perhaps you can find it useful and collaborate with some ideas!

**Comment by mvexel** [comment]
I'm closing this in favor of the ticket that @matheusgomesms referred to, since this is not really an API specific question, and I think it will benefit from broader discussion in the front-end repo.
