### ISSUE TITLE
Provide link to relation/way if area is too large

### ISSUE THREAD

**Issue by double-a** [maproulette/maproulette2#946]
I encountered the issue that I could not load the data via JOSM as the marked object was too large.
If the link to the object would be included (or at least textually) one could try to load the object directly (e.g. in the property overlay on the map).
Example: https://maproulette.org/challenge/13860/task/127851343

Other possibility: if the area is too large too load it should be sufficient to load the area around one of the waypoints to get the object.

**Comment by mvexel** [comment]
Hi @double-a  

This looks to be more of a MapRoulette front-end issue than an API issue. Could you please resubmit here: https://github.com/osmlab/maproulette3/issues 

Thanks!
