### ISSUE TITLE
geojson upload not recognized because of right hand rule, despite using force right hand rule in QGIS.

### ISSUE THREAD

**Issue by PCClimate** [maproulette/maproulette2#963]
When trying to upload a geojson file to a new MR challenge the file fails with "GeoJSON error: Polygons and MultiPolygons should follow the right-hand rule" despite applying the Force Right Hand Rule (native:forcerhr algorithm) in QGIS. The resulting geometries in the challenge are blank - there is only an outline in the widget, there is no data when opening the task in JOSM. 

Maproulette appears to be incorrectly detecting a right hand rule violation.

**Comment by mvexel** [comment]
Hi @PCClimate, 

This looks to be more of a MapRoulette front-end issue than an API issue. Could you please resubmit here: https://github.com/osmlab/maproulette3/issues 

Thanks!
