### ISSUE TITLE
"Unable to render the map: No value provided for variable {zoom}. Attempting to fall back to default map layer."

### ISSUE THREAD

**Issue by tordans** [maproulette/maproulette2#967]
I am getting this error https://maproulette.org/browse/challenges/26808

<img width="918" alt="image" src="https://user-images.githubusercontent.com/111561/184524656-8b28422d-4c13-49c9-9d79-a4dd835164b1.png">

The campaign does use a custom background `https://tiles.codefor.de/berlin-2020-truedop20rgb/{zoom}/{x}/{y}.png` but I don't see any issue here.

Console shows an error, but that is not helpful (I assume no source map is present in production so it's not easy to read?)

**Comment by mvexel** [comment]
Hi @tordans 

This looks to be more of a MapRoulette front-end issue than an API issue. Could you please resubmit here: https://github.com/osmlab/maproulette3/issues 

Thanks!
