### ISSUE TITLE
Changeset comment not included

### ISSUE THREAD

**Issue by angoca** [maproulette/maproulette2#977]
I have created a couple of challenges, but they never include a predefined text as part of the commit, even if I have specified.

This is one of the challenges: https://maproulette.org/admin/project/46513

This is the changeset description: #ColombiaDivisionPolitica #maproulette

What should I do to include a template for the commit message?

**Comment by mvexel** [comment]
Hi @angoca 

This sounds more like a MapRoulette front-end issue than an API issue. Could you please resubmit here: https://github.com/osmlab/maproulette3/issues

Thanks!
