### ISSUE TITLE
Challenge visibility is ambiguous in admin

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#99]
When a project is not set to Visible, a Challenge can still be set to Visible but it will not show up in search or challenge list.

Example:

<img width="1131" alt="screenshot 2016-06-10 10 41 00" src="https://cloud.githubusercontent.com/assets/120452/15971832/6056e9dc-2ef8-11e6-8d25-99f9257c548d.png">

<img width="1137" alt="screenshot 2016-06-10 10 41 07" src="https://cloud.githubusercontent.com/assets/120452/15971834/6428b52c-2ef8-11e6-8b28-2cc13a746066.png">

**Comment by mvexel** [comment]
As discussed: We will show a message at the top of the challenge list **if** the project is invisible saying:

`The parent Project is currently not Visible. Any Challenges you set to Visible will only become Visible if you also set the parent Project to Visible`.

Or something a little less wordy...

**Comment by mgcuthbert** [comment]
This is resolved as per the checkin for #132, and is pretty much a duplicate to #98
